# Generated by Django 4.2.3 on 2023-07-30 16:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300, validators=[django.core.validators.MinLengthValidator(10)])),
                ('date_of_publication', models.DateField(auto_now=True)),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('duration', models.DurationField()),
                ('location', models.CharField(max_length=100)),
            ],
        ),
    ]
