# Generated by Django 4.2.3 on 2023-07-28 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
    ]
