# Generated by Django 4.2.3 on 2023-07-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
