# Generated by Django 4.2.4 on 2023-08-04 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_publicationmodel_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationmodel',
            name='timestamp',
        ),
    ]
