# Generated by Django 4.2.3 on 2023-07-26 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioticsusermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=11),
            preserve_default=False,
        ),
    ]
