# Generated by Django 4.2.3 on 2023-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_bioticsusermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioticsusermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
