# Generated by Django 4.2.3 on 2023-07-30 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_bioticsapprover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioticsApprover',
        ),
    ]
