# Generated by Django 4.2.3 on 2023-07-27 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_bioticsusermodel_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioticsusermodel',
            name='biology_type',
            field=models.CharField(blank=True, choices=[('Botany', 'Botany'), ('Microbiology', 'Microbiology'), ('Zoology', 'Zoology')], max_length=13),
        ),
        migrations.AlterField(
            model_name='bioticsusermodel',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Other')], max_length=13),
        ),
        migrations.AlterField(
            model_name='bioticsusermodel',
            name='rank',
            field=models.CharField(blank=True, choices=[('Student', 'Student'), ('Assistant', 'Assistant'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=20),
        ),
    ]
