# Generated by Django 4.2.3 on 2023-07-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_bioticsusermodel_biology_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioticsusermodel',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
    ]
