# Generated by Django 4.2.3 on 2023-07-28 20:02

import Biotics.profiles.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_bioticsusermodel_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioticsusermodel',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True, validators=[Biotics.profiles.validators.age_validator]),
        ),
    ]
