# Generated by Django 4.2.4 on 2023-08-03 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0004_alter_trainingmodel_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
