# Generated by Django 4.2.4 on 2023-08-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_recipients'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='recipients',
            new_name='receiver',
        ),
    ]
