# Generated by Django 4.2.4 on 2023-08-08 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
